config/routes.rb
Rails.application.routes.draw do
    
 
 
  

  scope module: :public do
    root to:'homes#top' #どういうURLに飛ぶかは決まってるからアクション先だけ書く
    get 'about'=>'homes#about'#左側は勝手に決めていい
    get'customers/quit'=>  'customers#quit'
    patch'customers/out'=> 'customers#out'
    resource :customers,only:[:show ,:edit,:update]
    resources :addresses,only:[:create, :index,:edit,:update,:destroy]
    resources :items,only:[:index, :show]
    delete 'cart_items/destroy_all' =>'cart_items#destroy_all'
    resources :cart_items,only:[:create, :index,:update,:destroy]
    post 'orders/confirm'=>'orders#confirm'
    get 'orders/thanks'=>'orders#thanks'
    resources :orders,only:[:new, :create, :index,:show]
  end
  

  
  

  namespace :admin do
     root to:"homes#top"
     resources :orders,only:[:show ,:update]
     resources :customers,only:[ :index, :show ,:edit,:update]
     resources :items,only:[:new, :create, :index, :show ,:edit,:update]
     resources :genres,only:[:create, :index, :edit,:update]
     resources :order_details,only:[:update]
  end
  
  
 devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

end

app/models/address.rb
class Address < ApplicationRecord
    def address_disply
        '〒'+postal_code+''+address+''+name
    end    
    belongs_to :customer
    
    
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :name, presence: true
    
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
     belongs_to :item
      belongs_to :customer
      
  def get_image(width,height)
    unless image.attached?
   file_path=Rails.root.join('app/assets/images/no_image.jpg')
   image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
  image.variant(resize_to_limit: [width, height]).processed
  end    
      
      
  def subtotal
      item.with_tax_price*amount
  end 
end

app/models/customer.rb
class Customer < ApplicationRecord
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cart_items, dependent: :destroy    
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy
  
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true
  validates :email, presence: true
     
end

app/models/genre.rb
class Genre < ApplicationRecord
    
    has_many :items, dependent: :destroy
     
end     

app/models/item.rb
class Item < ApplicationRecord
 
    has_one_attached :image
    
     has_many :cart_items, dependent: :destroy
      has_many :order_details, dependent: :destroy
    
    belongs_to :genre
     
 def get_image(width,height)
  unless image.attached?
   file_path=Rails.root.join('app/assets/images/no_image.jpg')
   image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
  image.variant(resize_to_limit: [width, height]).processed
 end
 
 def add_tax_price
  (self.price * 1.10).round
 end
 
 def with_tax_price
  (price*1.1).floor
 end 
end 
 

app/models/order.rb
class Order < ApplicationRecord
    enum payment_method: { credit_card: 0, transfer: 1 }
    enum order_status: { waiting: 0,confirmation:1,paid_up:2, preparing:3, shipped:4 }
    enum making_status: { impossible_manufacture: 0, waiting_manufacture:1,manufacturing:2,finish:3}
     #has_many :items
     has_many :order_details
     belongs_to :customer
    
    def with_tax_price
        (price*1.1).floor 
    end 
    
    validates :postal_code, presence: true
    validates :address, presence: true
    validates :name, presence: true
    

 
     
     
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
     enum making_status: { impossible_manufacture: 0, waiting_manufacture:1,manufacturing:2,finish:3}
     belongs_to :item
     belongs_to :order
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController

  def index
    #@customers=Customer.all
    @customers=Customer.page(params[:page])
  end

  def show
    @customer=Customer.find(params[:id])
  end

  def edit
    @customer=Customer.find(params[:id])
  end
  
  def update
    @customer=Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customer_path(@customer)
  end
private

def customer_params
  params.require(:customer).permit(:last_name,:first_name,:last_name_kana,:first_name_kana,:email,:postal_code,:address,:telephone_number,:is_deleted)
end

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  
  
  def create
    @genre=Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
    
  end
  
  def index
    @genre=Genre.new
    @genres=Genre.all
  end

  def edit
    @genre=Genre.find(params[:id])
  end
  
  def update
    @genre=Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end
  private
  
  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
     @orders=Order.page(params[:page])
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def new
    @item=Item.new
  end
  
  def create
    @item=Item.new(item_params)
    @item.save
    #redirect_to admin_items_path
    redirect_to admin_item_path(@item.id)
  
  end  

  def index
    @items=Item.page(params[:page])
    #@items=Item.all
  end

  def show
    @item=Item.find(params[:id])
  end

  def edit
    @item=Item.find(params[:id])
  end
  
  def update
    @item=Item.find(params[:id])
    @item.update(item_params)
     #redirect_to admin_items_path
     redirect_to admin_item_path(@item)
    
  end  
  private
  
  def item_params
    params.require(:item).permit(:image,:name,:introduction,:price,:is_active,:genre_id)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  

  def show
    @sum=0
    @postage=800
    @order=Order.find(params[:id])
    @order_details=@order.order_details
  end

  def update
    @order=Order.find(params[:id])
    @order.update(order_params)
    if @order.order_status == "confirmation"#連動の書き方は最初にもしこうならこうするという結果を最初にかくとわかりやすい (16と１９）
      @order_details=@order.order_details#したの＠order_detailsだけだと定義がないからだめ
      
      @order_details.each do |order_detail| #何に対してupdateするのか書かないといけない(order_detailsに対して) 一回のupdateでは一つしかupdateできない order_details は複数だから(なぜなら一つの注文にいっぱいあるから)each文で一つずつupdateする
        @order_details.update(making_status: "waiting_manufacture")
      end
      
    end 
    redirect_to admin_order_path(@order)
  end
  
  def order_params
    params.require(:order).permit(:order_status)
  end
  
end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/views/admin/customers/edit.html.erb
<h2><%=@customer.last_name%><%=@customer.first_name%>さんの会員情報編集</h2>

<%=form_with model: @customer,url: admin_customer_path,method: :patch do |f| %>

<table>
    <tr><th>会員ID</th><td><%=@customer.id%></td></tr>
    <tr><th>氏名</th><td><%=f.search_field :last_name%><%=f.search_field :first_name%></td></tr>
    <tr><th>フリガナ</th><td><%=f.search_field :last_name_kana%><%=f.search_field :first_name_kana%></td></tr>
    <tr><th>郵便番号</th><td><%=f.text_field :postal_code%></td></tr>
    <tr><th>住所</th><td><%=f.text_field :address%></td></tr>
    <tr><th>電話番号</th><td><%=f.telephone_field :telephone_number%></td></tr>
    <tr><th>メールアドレス</th><td><%= f.email_field :email%></td></tr>
    <tr><th>会員ステータス</th><td><%=f.radio_button :is_deleted,false%>有効<%=f.radio_button :is_deleted,true%>退会</td></tr>
    <tr><th></th><td><%=f.submit'変更を保存' %></td></tr>
</table>
<%end%>

app/views/admin/customers/index.html.erb
<div class="container">
     <h2>会員一覧</h2>
    <div class="row justify-content-md-center">
        <div class="col-md-10">    
            <table>
                <thead>
                    <tr>
                        <th scope="col">会員ID</th>
                        <th scope="col">氏名</th>
                        <th scope="col">メールアドレス</th>
                        <th scope="col">ステータス</th>
                    </tr>
                </thead>
                <%@customers.each do |customer| %>
                <tbody>
                    <tr>
                        <td scope="row"><%=customer.id%></td>
                        <td>
                            <%=link_to admin_customer_path(customer.id) do%>
                            <%=customer.last_name%><%=customer.first_name%>
                            <%end%>
                        </td>    
                        <td><%=customer.email%></td>
                        <% if customer.is_deleted%>
                        <td>退会</td>
                        <%else%>
                        <td>有効</td>
                        <%end%>
                        
                    </tr>
                </tbody>
                <%end%>
           </table>
           <%= paginate @customers %>
       </div>
    </div>      
</div>

app/views/admin/customers/show.html.erb
<h2><%=@customer.last_name%><%=@customer.first_name%>さんの会員詳細</h2>

<table>
    <tr><th>会員ID</th><td><%=@customer.id%></td></tr>
    <tr><th>氏名</th><td><%=@customer.last_name%><%=@customer.first_name%>さんの会員詳細</td></tr>
    <tr><th>フリガナ</th><td><%=@customer.last_name_kana%><%=@customer.first_name_kana%></td></tr>
    <tr><th>郵便番号</th><td><%=@customer.postal_code%></td></tr>
    <tr><th>住所</th><td><%=@customer.address%></td></tr>
    <tr><th>電話番号</th><td><%=@customer.telephone_number%></td></tr>
    <tr><th>メールアドレス</th><td><%=@customer.email%></td></tr>
    <tr><th>会員ステータス</th><%if @customer.is_deleted%>
    <td>退会</td>
    <%else%>
    <td>有効</td>
    <%end%>

    
</table>

<%=link_to "編集する",edit_admin_customer_path(@customer),class:"btn btn-sm btn-success"%>
<%=link_to "注文履歴一覧を見る",admin_root_path,class:"btn btn-sm btn-danger"%>