config/routes.rb
Rails.application.routes.draw do
    
 
 
  

  scope module: :public do
    root to:'homes#top' #どういうURLに飛ぶかは決まってるからアクション先だけ書く
    get 'about'=>'homes#about'#左側は勝手に決めていい
    get'customers/quit'=>  'customers#quit'
    patch'customers/out'=> 'customers#out'
    resource :customers,only:[:show ,:edit,:update]
    resources :addresses,only:[:create, :index,:edit,:update,:destroy]
    resources :items,only:[:index, :show]
    delete 'cart_items/destroy_all' =>'cart_items#destroy_all'
    resources :cart_items,only:[:create, :index,:update,:destroy]
    post 'orders/confirm'=>'orders#confirm'
    get 'orders/thanks'=>'orders#thanks'
    resources :orders,only:[:new, :create, :index,:show]
  end
  

  
  

  namespace :admin do
     root to:"homes#top"
     resources :orders,only:[:show ,:update]
     resources :customers,only:[ :index, :show ,:edit,:update]
     resources :items,only:[:new, :create, :index, :show ,:edit,:update]
     resources :genres,only:[:create, :index, :edit,:update]
     resources :order_details,only:[:update]
  end
  
  
 devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

end

app/models/address.rb
class Address < ApplicationRecord
    def address_disply
        '〒'+postal_code+''+address+''+name
    end    
    belongs_to :customer
    
    
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :name, presence: true
    
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
     belongs_to :item
      belongs_to :customer
      
  def get_image(width,height)
    unless image.attached?
   file_path=Rails.root.join('app/assets/images/no_image.jpg')
   image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
  image.variant(resize_to_limit: [width, height]).processed
  end    
      
      
  def subtotal
      item.with_tax_price*amount
  end 
end

app/models/customer.rb
class Customer < ApplicationRecord
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cart_items, dependent: :destroy    
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy
  
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true
  validates :email, presence: true
     
end

app/models/genre.rb
class Genre < ApplicationRecord
    
    has_many :items, dependent: :destroy
     
end     

app/models/item.rb
class Item < ApplicationRecord
 
    has_one_attached :image
    
     has_many :cart_items, dependent: :destroy
      has_many :order_details, dependent: :destroy
    
    belongs_to :genre
     
 def get_image(width,height)
  unless image.attached?
   file_path=Rails.root.join('app/assets/images/no_image.jpg')
   image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
  image.variant(resize_to_limit: [width, height]).processed
 end
 
 def add_tax_price
  (self.price * 1.10).round
 end
 
 def with_tax_price
  (price*1.1).floor
 end 
end 
 

app/models/order.rb
class Order < ApplicationRecord
    enum payment_method: { credit_card: 0, transfer: 1 }
    enum order_status: { waiting: 0,confirmation:1,paid_up:2, preparing:3, shipped:4 }
    enum making_status: { impossible_manufacture: 0, waiting_manufacture:1,manufacturing:2,finish:3}
     #has_many :items
     has_many :order_details
     belongs_to :customer
    
    def with_tax_price
        (price*1.1).floor 
    end 
    
    validates :postal_code, presence: true
    validates :address, presence: true
    validates :name, presence: true
    

 
     
     
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
     enum making_status: { impossible_manufacture: 0, waiting_manufacture:1,manufacturing:2,finish:3}
     belongs_to :item
     belongs_to :order
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  
  
  def create
    @genre=Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
    
  end
  
  def index
    @genre=Genre.new
    @genres=Genre.all
  end

  def edit
    @genre=Genre.find(params[:id])
  end
  
  def update
    @genre=Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end
  private
  
  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
     @orders=Order.page(params[:page])
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def new
    @item=Item.new
  end
  
  def create
    @item=Item.new(item_params)
    @item.save
    #redirect_to admin_items_path
    redirect_to admin_item_path(@item.id)
  
  end  

  def index
    @items=Item.page(params[:page])
    #@items=Item.all
  end

  def show
    @item=Item.find(params[:id])
  end

  def edit
    @item=Item.find(params[:id])
  end
  
  def update
    @item=Item.find(params[:id])
    @item.update(item_params)
     #redirect_to admin_items_path
     redirect_to admin_item_path(@item)
    
  end  
  private
  
  def item_params
    params.require(:item).permit(:image,:name,:introduction,:price,:is_active,:genre_id)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  

  def show
    @sum=0
    @postage=800
    @order=Order.find(params[:id])
    @order_details=@order.order_details
  end

  def update
    @order=Order.find(params[:id])
    @order.update(order_params)
    if @order.order_status == "confirmation"#連動の書き方は最初にもしこうならこうするという結果を最初にかくとわかりやすい (16と１９）
      @order_details=@order.order_details#したの＠order_detailsだけだと定義がないからだめ
      
      @order_details.each do |order_detail| #何に対してupdateするのか書かないといけない(order_detailsに対して) 一回のupdateでは一つしかupdateできない order_details は複数だから(なぜなら一つの注文にいっぱいあるから)each文で一つずつupdateする
        @order_details.update(making_status: "waiting_manufacture")
      end
      
    end 
    redirect_to admin_order_path(@order)
  end
  
  def order_params
    params.require(:order).permit(:order_status)
  end
  
end 

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/views/admin/genres/edit.html.erb
<h2>ジャンル編集</h2>

<%=form_with model: @genre,url: admin_genre_path,method: :patch do |f| %>
 <table>
  <tr><th>ジャンル名</th><td><%=f.text_field:name%></td><td><%=f.submit"変更を保存"%></td></tr>
 </table>
<%end%>

app/views/admin/genres/index.html.erb
<div class="container">
  <h3>ジャンル一覧　ジャンル追加</h3>
  
  <%=form_with model: @genre,url: admin_genres_path do |f| %>
  
   <table>
     <tr><th>ジャンル名</th><td><%=f.text_field:name%></td><td><%=f.submit'新規登録',class:"btn btn-sm btn-success"%></td></tr>
   </table>
  <%end%>
  
    <table class="table col-md-3">
      <thead>
        <tr>
          <th acope=>ジャンル</th>
        </tr>
      </thead>
    <%@genres.each do |genre|%>
      <tbody>
        <tr>
          <td scope="row"><%=genre.name%></td>
          <td><%=link_to"編集する",edit_admin_genre_path(genre.id),class:"btn btn-sm btn-success"%></td>
        </tr>
      </tbody>
    <%end%>
  </table>

</div>
 

app/views/admin/items/edit.html.erb
<h2>商品編集</h2>

<%=form_with model: @item,url: admin_item_path,method: :patch do |f| %>


 <table>
    <tr><th>商品画像</th><td><%=f.file_field :image,accept:"image/*"%></td></tr>
    <tr><th>商品名</th><td><%=f.text_field:name%></td></tr>
    <tr><th>商品説明</th><td><%=f.text_area:introduction%></td></tr>
    <tr><th>税抜価格</th><td><%=f.text_field:price%>円</td></tr>
    <tr><th>販売ステータス</th><td><%=f.radio_button:is_active,true%>販売中<%=f.radio_button:is_active,false%>販売停止中</td></tr>
    <tr><th></th><td><%=f.submit'変更を保存' %></td></tr>
 </table>
<%end%>

app/views/admin/items/index.html.erb
<div class="container">
     <h2>商品一覧</h2>
    <div class="row justify-content-md-center">
         <div class="col-md-10">    
            <table class="table">
             <thead>
                <tr>
                     <th scope="col">商品ID</th>
                     <th scope="col">商品名</th>
                     <th scope="col">税抜価格</th>
                     <th scope="col">ジャンル</th>
                     <th scope="col">ステータス</th>
                </tr> 
             <thead>
              <%@items.each do |item|%>
              <tbody>
                  <tr>
                      <td scope="row"><%=item.id%></td>
                      <td><%=link_to item.name,admin_item_path(item.id)%></td>
                      <td><%=item.price%></td>
                      <td><%=item.genre.name%></td>
                      <td><%if item.is_active%>
                      <p>販売中</p>
                         <%else%>
                      <p>販売停止中</p>   
                         <%end%>
                      </td>
                  </tr>
              </tbody>
              <%end%>
            </table>
            <%= paginate @items %>
            <%=link_to "商品新規登録",new_admin_item_path,class:"btn btn-sm btn-success"%>
        </div>    
    </div>
</div>

app/views/admin/items/new.html.erb
<div class="container">
    <h2>商品新規登録</h2>
    <div class="row justify-content-md-center">
        <div class="col-md-6">    
            <%=form_with model: @item,url: admin_items_path do |f| %>
            
            <table>
                <tr><th>商品画像</th><td><%=f.file_field :image,accept:"image/*"%></td></tr>
                <tr><th>商品名</th><td><%=f.text_field:name,placeholder:"商品名"%></td></tr>
                <tr><th>商品説明</th><td><%=f.text_area:introduction,placeholder:"ここに説明文を記述します"%></td></tr>
                <tr><th>ジャンル</th><td><%=f.collection_select:genre_id,Genre.all,:id,:name%></td></tr>
                <tr><th>税抜価格</th><td><%=f.text_field:price,placeholder:"1000"%>円</td></tr>
                <tr><th>販売ステータス</th><td><%=f.radio_button:is_active,true%>販売中<%=f.radio_button:is_active,false%>販売停止中</td></tr>
                <tr><th></th><td><%=f.submit'新規登録'%></td></tr>
             </table>
            <%end%>
        </div>
    </div>
</div>
  

app/views/admin/items/show.html.erb
 <div class="container">
     <div class="row">
           
        <div class="col-md-2">
        　　<H2>商品詳細</H2>
           <%=image_tag @item.get_image(200,130)%>
        </div>
       <div class="col-md-3">
        <table>
                <tr><th>商品名</th><td><%=@item.name%></td></tr>
                
                <tr><th>商品説明</th><td><%=@item.introduction%></td></tr>
                
                <tr><th>ジャンル</th><td><%=@item.genre.name%></td></tr>
                
                <tr><th>税込価格<br>(税抜価格)</th><td><%= @item.add_tax_price.to_s(:delimited) %>(<%=@item.price%>)円</td></tr>
                
                <tr><th>販売ステータス</th><td><% if @item.is_active%><p>販売中</p><%else%><P>販売停止中</P><%end%></td></tr>
        </table>
        <%=link_to "編集する",edit_admin_item_path(@item)%>
        </div>
    </div>    
</div>

app/views/admin/orders/show.html.erb
<h1>注文履歴詳細</h1>


<table>
    <tr><th>購入者</th><td><%=link_to @order.name,admin_customer_path(@order.customer.id)%></td></tr><%#(customer.id)だけだとundefined local variable or method `customerエラーになるなぜならcustomerの定義をコントやビューでしていないからだから@orderをつける%>
    
    <tr><th>注文日</th><td><%=@order.created_at.strftime('%Y/%m/%d') %></td></tr>
    <tr><th>配送先</th><td>〒<%=@order.address%></td></tr>
    <tr><th>支払方法</th><td><%=@order.payment_method_i18n%></td></tr>
    <tr><th>注文ステータス</th>
    <%if @order.order_status==1%>
    <%end%>
    <td><%=form_with model: @order,url: admin_order_path do |f| %>
   <%=f.select :order_status,[["入金待ち","waiting"], ["入金確認","confirmation"], ["制作中","paid_up"],["発送準備中","preparing"],["発送済み","shipped"]]%>
    <%=f.submit '更新',class:"btn btn-sm btn-success"%></td></tr>
   <%end%>
</table>

<table class="table col-md-6">
    <thead>
        <tr>
            <th scope="col">商品名</th>
            <th scope="col">単価(税込)</th>
            <th scope="col">数量</th>
            <th scope="col">小計</th>
            <th scope="col">製作ステータス</tH>
        </tr>
    </thead>
    <tbody>
        <% @order_details.each do |order_detail|%>
        <tr>
            <td><%=order_detail.item.name%></td> 
            <td><%=order_detail.item.with_tax_price%></td>
            <td><%=order_detail.amount%></td>
            <td><%=order_detail.item.with_tax_price*order_detail.amount%></td>
                <%@sum+=order_detail.item.with_tax_price*order_detail.amount%>
            <td> <%=form_with model: order_detail,url: admin_order_detail_path(order_detail) do |f| %><%#patch書かなくても元々フォームに値が入っていると勝手にpatchになる%>
             <%=f.select :making_status,[["着手不可","impossible_manufacture"], ["制作待ち","waiting_manufacture"], ["制作中","manufacturing"],["制作完了","finish"]]%>
            <%=f.submit '更新',class:"btn btn-sm btn-success"%></td>
            <%end%>
        </tr>
        <%end%>
    </tbody>
</table>

<div class="col-md-6">
<table>
    <tr><th>商品合計</th><td><%=@sum%>円</td></tr>
    <tr><th>送料</th><td><%=@postage%>円</td></tr>
    <tr><th>請求金額合計</th><td><%=@sum+=@postage%>円</td></tr>
</table>