config/routes.rb
Rails.application.routes.draw do
    
 
 
  

  scope module: :public do
    root to:'homes#top' #どういうURLに飛ぶかは決まってるからアクション先だけ書く
    get 'about'=>'homes#about'#左側は勝手に決めていい
    get'customers/quit'=>  'customers#quit'
    patch'customers/out'=> 'customers#out'
    resource :customers,only:[:show ,:edit,:update]
    resources :addresses,only:[:create, :index,:edit,:update,:destroy]
    resources :items,only:[:index, :show]
    delete 'cart_items/destroy_all' =>'cart_items#destroy_all'
    resources :cart_items,only:[:create, :index,:update,:destroy]
    post 'orders/confirm'=>'orders#confirm'
    get 'orders/thanks'=>'orders#thanks'
    resources :orders,only:[:new, :create, :index,:show]
  end
  

  
  

  namespace :admin do
     root to:"homes#top"
     resources :orders,only:[:show ,:update]
     resources :customers,only:[ :index, :show ,:edit,:update]
     resources :items,only:[:new, :create, :index, :show ,:edit,:update]
     resources :genres,only:[:create, :index, :edit,:update]
     resources :order_details,only:[:update]
  end
  
  
 devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

end

app/models/address.rb
class Address < ApplicationRecord
    def address_disply
        '〒'+postal_code+''+address+''+name
    end    
    belongs_to :customer
    
    
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :name, presence: true
    
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
     belongs_to :item
      belongs_to :customer
      
  def get_image(width,height)
    unless image.attached?
   file_path=Rails.root.join('app/assets/images/no_image.jpg')
   image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
  image.variant(resize_to_limit: [width, height]).processed
  end    
      
      
  def subtotal
      item.with_tax_price*amount
  end 
end

app/models/customer.rb
class Customer < ApplicationRecord
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cart_items, dependent: :destroy    
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy
  
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true
  validates :email, presence: true
     
end

app/models/genre.rb
class Genre < ApplicationRecord
    
    has_many :items, dependent: :destroy
     
end     

app/models/item.rb
class Item < ApplicationRecord
 
    has_one_attached :image
    
     has_many :cart_items, dependent: :destroy
      has_many :order_details, dependent: :destroy
    
    belongs_to :genre
     
 def get_image(width,height)
  unless image.attached?
   file_path=Rails.root.join('app/assets/images/no_image.jpg')
   image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
  image.variant(resize_to_limit: [width, height]).processed
 end
 
 def add_tax_price
  (self.price * 1.10).round
 end
 
 def with_tax_price
  (price*1.1).floor
 end 
end 
 

app/models/order.rb
class Order < ApplicationRecord
    enum payment_method: { credit_card: 0, transfer: 1 }
    enum order_status: { waiting: 0,confirmation:1,paid_up:2, preparing:3, shipped:4 }
    enum making_status: { impossible_manufacture: 0, waiting_manufacture:1,manufacturing:2,finish:3}
     #has_many :items
     has_many :order_details
     belongs_to :customer
    
    def with_tax_price
        (price*1.1).floor 
    end 
    
    validates :postal_code, presence: true
    validates :address, presence: true
    validates :name, presence: true
    

 
     
     
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
     enum making_status: { impossible_manufacture: 0, waiting_manufacture:1,manufacturing:2,finish:3}
     belongs_to :item
     belongs_to :order
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
     @orders=Order.page(params[:page])
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def new
    @item=Item.new
  end
  
  def create
    @item=Item.new(item_params)
    @item.save
    #redirect_to admin_items_path
    redirect_to admin_item_path(@item.id)
  
  end  

  def index
    @items=Item.page(params[:page])
    #@items=Item.all
  end

  def show
    @item=Item.find(params[:id])
  end

  def edit
    @item=Item.find(params[:id])
  end
  
  def update
    @item=Item.find(params[:id])
    @item.update(item_params)
     #redirect_to admin_items_path
     redirect_to admin_item_path(@item)
    
  end  
  private
  
  def item_params
    params.require(:item).permit(:image,:name,:introduction,:price,:is_active,:genre_id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%#= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/801a1ac1e5.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %> <%#ブートストラップ使う場合外す%>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-white bg-white">
        <div class="container">
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
      　<%=link_to'ながのCAKE',root_path%>
          <% if admin_signed_in?%>
            <li>
              <%=link_to'商品一覧',admin_items_path,class: 'nav-link text-dark'%>
            </li>
            <li>
              <%=link_to'会員一覧',admin_customers_path,class: 'nav-link text-dark'%>
            </li>
            <li>
              <%=link_to'注文履歴一覧',admin_root_path,class: 'nav-link text-dark'%>
            </li>
            <li>
              <%=link_to'ジャンル一覧',admin_genres_path,class: 'nav-link text-dark'%>
            </li>
            <li>
              <%=link_to"ログアウト",destroy_admin_session_path,method: :delete,class: 'nav-link text-dark'%>
            </li>
          <% elsif customer_signed_in?%>
            <li>
            ようこそ、<%=current_customer.first_name%>さん!
            </li>
            <li>
              <%=link_to "マイページ",customers_path,class: 'nav-link text-dark'%>
            </li>
            <li>
              <%=link_to"商品一覧",items_path,class: 'nav-link text-dark'%>
            </li>
            <Li>
              <%=link_to"カート",cart_items_path,class: 'nav-link text-dark'%>
            </Li>
            <li>
               <%=link_to"ログアウト",destroy_customer_session_path,method: :delete,class: 'nav-link text-dark'%>
            </li>
          <%else%>
            <li>
              <%=link_to"About",about_path,class: 'nav-link text-dark'%>
            </li>
            <li>
              <%=link_to"商品一覧",items_path,class: 'nav-link text-dark'%>
            </li>
            <li>
              <%=link_to"新規登録", new_customer_registration_path,class: 'nav-link text-dark'%>
            </li>
            <li>
              <%=link_to"ログイン",new_customer_session_path,class: 'nav-link text-dark'%>
            </li>
          <%end%>
        </div>  
    </header>
    
    <%= yield %>
  </body>
</html>